### ISSUE TITLE
Symfony\Component\EventDispatcher\Event not found while loading

### ISSUE THREAD

**Issue by outrank-james** [FriendlyDotCH/mautic-multi-domain#22]
Just tried this in the new Mautic 5 alfa - seems that there's references to missing packages for this version. 

Just a heads up for when Mautic 5 is released.

**Comment by outrank-james** [comment]
`Error: During inheritance of MauticPlugin\MauticMultiDomainBundle\Model\MultidomainModel, while autoloading Symfony\Component\EventDispa  
  tcher\Event: Uncaught ReflectionException: Class "Symfony\Component\EventDispatcher\Event" not found while loading "MauticPlugin\MauticM  
  ultiDomainBundle\Model\MultidomainModel". in /home/nginx/domains/domain.com/public/vendor/composer/ClassLoader.php:576           
  Stack trace:                                                                                                                              
  #0 [internal function]: Composer\Autoload\ClassLoader->loadClass('...')                                                                   
  #1 /home/nginx/domains/domain.com/public/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('...')      
  #2 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/ContainerBuilder.php(370): Symfony\Component\Confi  
  g\Resource\ClassExistenceResource->isFresh(0)                                                                                             
  #3 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Loader/FileLoader.php(217): Symfony\Component\Depe  
  ndencyInjection\ContainerBuilder->getReflectionClass('...')                                                                               
  #4 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Loader/FileLoader.php(105): Symfony\Component\Depe  
  ndencyInjection\Loader\FileLoader->findClasses('...', '...', Array, Object(Symfony\Component\DependencyInjection\Compiler\RegisterAutoco  
  nfigureAttributesPass))                                                                                                                   
  #5 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Loader/Configurator/PrototypeConfigurator.php(69):  
   Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), '...  
  ', '...', Array)                                                                                                                          
  #6 /home/nginx/domains/domain.com/public/app/config/services.php(30): Symfony\Component\DependencyInjection\Loader\Configurator  
  \PrototypeConfigurator->__destruct()                                                                                                      
  #7 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(151): Symfony\Component\D  
  ependencyInjection\Loader\ProtectedPhpFileLoader->Symfony\Component\DependencyInjection\Loader\Configurator\{closure}(Object(Symfony\Com  
  ponent\DependencyInjection\Loader\Configurator\ContainerConfigurator), Object(Symfony\Component\DependencyInjection\Compiler\MergeExtens  
  ionConfigurationContainerBuilder))                                                                                                        
  #8 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(67): Symfony\Component\De  
  pendencyInjection\Loader\PhpFileLoader->executeCallback(Object(Closure), Object(Symfony\Component\DependencyInjection\Loader\Configurato  
  r\ContainerConfigurator), '...')                                                                                                          
  #9 /home/nginx/domains/domain.com/public/app/bundles/CoreBundle/DependencyInjection/MauticCoreExtension.php(36): Symfony\Compon  
  ent\DependencyInjection\Loader\PhpFileLoader->load('...')                                                                                 
  #10 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76):  
   Mautic\CoreBundle\DependencyInjection\MauticCoreExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExten  
  sionConfigurationContainerBuilder))                                                                                                       
  #11 /home/nginx/domains/domain.com/public/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42  
  ): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\  
  ContainerBuilder))                                                                                                                        
  #12 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\Http  
  Kernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))       
  #13 /home/nginx/domains/domain.com/public/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\Depe  
  ndencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))                                
  #14 /home/nginx/domains/domain.com/public/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\Con  
  tainerBuilder->compile()                                                                                                                  
  #15 /home/nginx/domains/domain.com/public/app/AppKernel.php(256): Symfony\Component\HttpKernel\Kernel->initializeContainer()     
  #16 /home/nginx/domains/domain.com/public/vendor/symfony/http-kernel/Kernel.php(146): AppKernel->boot()                          
  #17 /home/nginx/domains/domain.com/public/vendor/symfony/framework-bundle/Command/CacheClearCommand.php(237): Symfony\Component  
  \HttpKernel\Kernel->reboot('...')                                                                                                         
  #18 /home/nginx/domains/domain.com/public/vendor/symfony/framework-bundle/Command/CacheClearCommand.php(149): Symfony\Bundle\Fr  
  ameworkBundle\Command\CacheClearCommand->warmup('...', '...')                                                                             
  #19 /home/nginx/domains/domain.com/public/vendor/symfony/console/Command/Command.php(298): Symfony\Bundle\FrameworkBundle\Comma  
  nd\CacheClearCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))  
  #20 /home/nginx/domains/domain.com/public/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Comma  
  nd->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                        
  #21 /home/nginx/domains/domain.com/public/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Consol  
  e\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand), Object(Symfony\Component\Console\Input\Arg  
  vInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                          
  #22 /home/nginx/domains/domain.com/public/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\A  
  pplication->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand), Object(Symfony\Component\Console\Input\ArgvIn  
  put), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                             
  #23 /home/nginx/domains/domain.com/public/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Consol  
  e\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))           
  #24 /home/nginx/domains/domain.com/public/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\A  
  pplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))              
  #25 /home/nginx/domains/domain.com/public/bin/console(13): Symfony\Component\Console\Application->run(Object(Symfony\Component\  
  Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                         
  #26 {main}    `

**Comment by jos0405** [comment]
Thank you, we'll update it once 5.1 is out, not earlier.

**Comment by jos0405** [comment]
But keep it open :)

**Comment by namnhfreelancer** [comment]
Mautic 5.1 released from 12, 06, 2024. Did you plan update it ?

**Comment by mzagmajster** [comment]
@jos0405 is this still an issue?
